# zuul是netflix开源的一个API Gateway 服务器, 本质上是一个web servlet应用
zuul: 
   # 重制机制
   retryable: true
   
   # 所有服务敏感头不过滤
   sensitive-headers: 
   max:
      host:
         connections: 500
   host:
      maxTotalConnections: 200
      maxPerRouteConnection: 20
   routes:
      # 标识你的服务名称，可以自己任意定义
      service-rpc-user:
         path: /user/**
         service-id: user-server
         
      # 服务名：拦截的路径
      product-server: /product/**
      order-server: /order/**
      
ribbon:
   ConnectionTimeout: 3000
   ReadTomeout: 5000
   OkToRetryOnAllOperations: true
   MaxAutoRetriesNextServer: 2
   MaxAutoRetries: 1
   
# 配置hystrix全局默认的超时
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 3000
                  